#!/usr/bin/ruby
#  Blog  : https://meniny.cn
#  Github: https://github.com/Meniny
#
#  No more shall we pray for peace
#  Never ever ask them why
#  No more shall we stop their visions
#  Of selfdestructing genocide
#  Dogs on leads march to war
#  Go ahead end it all...
#
#  Blow up the world
#  The final silence
#  Blow up the world
#  I don't give a damn!
#
#  Screams of terror, panic spreads
#  Bombs are raining from the sky
#  Bodies burning, all is dead
#  There's no place left to hide
#  Dogs on leads march to war
#  Go ahead end it all...
#
#  Blow up the world
#  The final silence
#  Blow up the world
#  I don't give a damn!
#
#  (A voice was heard from the battle field)
#
#  "Couldn't care less for a last goodbye
#  For as I die, so do all my enemies
#  There's no tomorrow, and no more today
#  So let us all fade away..."
#
#  Upon this ball of dirt we lived
#  Darkened clouds now to dwell
#  Wasted years of man's creation
#  The final silence now can tell
#  Dogs on leads march to war
#  Go ahead end it all...
#
#  Blow up the world
#  The final silence
#  Blow up the world
#  I don't give a damn!
#
#  When I wrote this code, only I and God knew what it was.
#  Now, only God knows!
#
#  So if you're done trying 'optimize' this routine (and failed),
#  please increment the following counter
#  as a warning to the next guy:
#
#  total_hours_wasted_here = 0
#
#  Created by Elias Abel on 2017/12/15.
#  Copyright © 2017 MobiMagic. All rights reserved.
#

source 'https://github.com/CocoaPods/Specs.git'
project './Sample.xcodeproj'
platform :ios, '9.0'

use_frameworks!

inhibit_all_warnings!

pre_install do |installer|

end

# Elias Abel ==============================
def elias()
    # pod 'SystemSounds' # Sounds player
    # pod 'JustLayout' # AutoLayout sugar
    # pod 'InfoPlist' # Info.plist assistant.
    # pod 'EasyGCD' # GCD
    # pod 'Observing' # NotificationCenter stuffs
    # pod 'Every' # Sugar for NSTimer


end

abstract_target 'ParamountDialogsSample' do

  pod 'ParamountDialogs', :path => '../'

  elias()

  # Common ==== ==============================
  # pod 'Kingfisher' # Kingfisher
  # pod 'Gifu'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['SWIFT_VERSION'].nil? == false
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
    end
  end

  target 'Sample' do
    # Nothing
  end

end
